### ISSUE TITLE
[Feature Request] Support for Load Balancer Service Type

### ISSUE THREAD

**Issue by ApatheticRiku** [rm3l/helm-charts#39]
Currently, users can select the type of kubernetes service for each DNS service running on the chart (NodePort/ClusterIP). However, the use case I have is to set up the DNS (just standard DNS port 53) service as type LoadBalancer.
I'm able to set the service type to LoadBalancer without a problem, but the chart values do not account for specifying a LoadBalancerIP.
I am running MetalLB on my cluster, so adguard is taking the first available IP in MetalLB's range, which is fine for now, but I would prefer to be able to specify the LoadBalancerIP value in the chart definition.

**Comment by rm3l** [comment]
@ApatheticRiku thanks for opening this issue.

Yeah, adding `loadBalancerIP` definitely makes sense. I'll look into adding this when I get a chance.

Thanks!

**Comment by rm3l** [comment]
FYI, this should be fixed now. A new version of this Chart has been published accordingly: [0.10.0](https://github.com/rm3l/helm-charts/releases/tag/adguard-home-0.10.0).

Please do let me know if you run into any issues with these changes.
