### ISSUE TITLE
Adguard: Extra Volumes/VolumeMounts

### ISSUE THREAD

**Issue by simbaja** [rm3l/helm-charts#50]
Any chance you can update the helm chart to include the ability to specify extra volumes and volume mounts (similar to some of the bitnami charts)?  Was looking to mount certificates from lets encrypt from a secret into a volume and let Adguard pick them up instead of the self signed certs.

**Comment by rm3l** [comment]
Hi @simbaja,
Good idea. Feel free to go ahead and create a PR ;-)
Thanks.
