### ISSUE TITLE
adguard home service annotations

### ISSUE THREAD

**Issue by fwmarcel** [rm3l/helm-charts#67]
Hello,

first of all thanks for the helm charts.
Could you add a possibility to set annotations to the services for Adguard Home?
I would like to use the type as a load balancer. However, this service needs annotations so that it always gets the same IP. 

Thanks in advance!

**Comment by rm3l** [comment]
Hi @fwmarcel ,
Thanks for this feature request, which makes a lot of sense.
Interested in contributing a PR?

**Comment by fwmarcel** [comment]
@rm3l  since I can't get any further, I have added this here. please take a look at it

**Comment by rm3l** [comment]
> since I can't get any further, I have added this here. please take a look at it

Thanks @fwmarcel. Please take a look at my review comments.
