### ISSUE TITLE
AdGuard - Option to configure `externalTrafficPolicy` for services

### ISSUE THREAD

**Issue by m-wrzesien** [rm3l/helm-charts#72]
Hello,

Thank you for a really nice chart for AdGuard :D

I've come with a little feature request:
In case of using service type `LoadBalancer` or `NodePort` Kubernetes by default won't preserve IP address of the clients that are outside of cluster.
To address that, field `externalTrafficPolicy` needs to be set to value `Local` instead of default `Cluster`.

Will you be interested in this feature?
I have code ready for it on my fork and could provide it via PR.

**Comment by rm3l** [comment]
Hi @m-wrzesien,
Thanks.
Yes, that feature would definitely be useful. So please go ahead and raise a PR.
